#!/usr/bin/env python3
"""Validate and roll up the Hustle & Heir asset checklist corpus.

The checklist lives in docs/asset-checklist/*.md. Every trackable deliverable is a
markdown checkbox line in the canonical form:

    - [ ] `ASSET-ID` — Human readable description. [S] [P0]

    status  : [ ] open, [x] done, [-] deferred/wontfix
    id      : upper-case, dash-separated, registered prefix (see PREFIXES)
    source  : [S] specified in the original brief, [D] derived/expanded here
    prio    : [P0] vertical slice, [P1] alpha, [P2] beta/launch

The script is the project's own check over the checklist: it fails on malformed or
duplicate IDs, fails if the brief's numeric requirements are not met, and fails if
the roll-up block committed in the index is stale.

Usage:
    python3 tools/check_checklist.py            # validate + print roll-up
    python3 tools/check_checklist.py --write    # ...and refresh the roll-up block in the index
    python3 tools/check_checklist.py --check    # fail if the committed roll-up is stale
    python3 tools/check_checklist.py --csv OUT  # export every item to CSV
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import Counter, OrderedDict, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs" / "asset-checklist"
INDEX = DOCS / "README.md"

ROLLUP_START = "<!-- ROLLUP:START (generated by tools/check_checklist.py --write) -->"
ROLLUP_END = "<!-- ROLLUP:END -->"

# prefix -> (domain, short label)
PREFIXES = {
    "CHR-BODY": ("Characters & Animation", "Base body frames"),
    "CHR-BASE": ("Characters & Animation", "Base-mesh pipeline"),
    "CHR-FACE": ("Characters & Animation", "Face morph sliders"),
    "CHR-HAIR": ("Characters & Animation", "Hairstyles"),
    "CHR-BRD": ("Characters & Animation", "Facial hair"),
    "CHR-EYE": ("Characters & Animation", "Iris patterns"),
    "CHR-CLR": ("Characters & Animation", "Colour spectrums"),
    "CHR-DECAL": ("Characters & Animation", "Scar / tattoo patterns"),
    "TEX": ("Characters & Animation", "Texture maps & atlases"),
    "WRD": ("Characters & Animation", "Wardrobe layers & implants"),
    "ANM-LOC": ("Characters & Animation", "Animation - locomotion"),
    "ANM-MEL": ("Characters & Animation", "Animation - melee movesets"),
    "ANM-MA": ("Characters & Animation", "Animation - martial arts styles"),
    "ANM-TAC": ("Characters & Animation", "Animation - tactical"),
    "ANM-CRF": ("Characters & Animation", "Animation - crafting & interaction"),
    "ANM-VEH": ("Characters & Animation", "Animation - vehicles"),
    "ANM-FAC": ("Characters & Animation", "Animation - face & emote"),
    "ANM-RIG": ("Characters & Animation", "Rig & animation tech"),
    "ENV": ("World & Environment", "District modular kits"),
    "ENV-WX": ("World & Environment", "Dynamic weather VFX"),
    "ENV-SPS": ("World & Environment", "Spiritual Storms"),
    "ENV-ASG": ("World & Environment", "Arcane Surges"),
    "ENV-CYC": ("World & Environment", "Day/night cycle"),
    "VEH": ("World & Environment", "Vehicles"),
    "INT-HRV": ("World & Environment", "Harvestable nodes"),
    "INT-FUR": ("World & Environment", "Property furniture & props"),
    "CFT": ("Crafting & Combat Props", "Crafting workstations"),
    "RAW": ("Crafting & Combat Props", "Raw materials"),
    "WPN-MEL": ("Crafting & Combat Props", "Melee arsenal"),
    "WPN-RNG": ("Crafting & Combat Props", "Ranged arsenal"),
    "WPN-THR": ("Crafting & Combat Props", "Throwables"),
    "UI": ("UI, Magic & System Overlays", "Interface"),
    "MAG-SHP": ("UI, Magic & System Overlays", "Spell drawing shapes"),
    "MAG-DRW": ("UI, Magic & System Overlays", "Spell draw canvas system"),
    "MAG-GRM": ("UI, Magic & System Overlays", "Grimoire & runes"),
    "MAG-MER": ("UI, Magic & System Overlays", "Meridian overlays"),
    "AUR": ("UI, Magic & System Overlays", "Persona auras"),
    "AUR-SYS": ("UI, Magic & System Overlays", "Aura system / budget governor"),
    "CR": ("Career Paths", "Career wardrobe / tools / VFX"),
}

DOMAIN_ORDER = [
    "Characters & Animation",
    "World & Environment",
    "Crafting & Combat Props",
    "UI, Magic & System Overlays",
    "Career Paths",
]

DISTRICTS = OrderedDict(
    [
        ("DTC", "Downtown Core"),
        ("UNI", "University"),
        ("OLD", "Old Town"),
        ("IND", "Industrial"),
        ("ENT", "Entertainment"),
        ("WTR", "Waterfront"),
        ("SUB", "Suburbs"),
        ("MYH", "Mystic Heights"),
        ("ARC", "Arcane District"),
        ("UND", "Underground"),
        ("RUR", "Rural"),
        ("GOV", "Government Center"),
    ]
)

CAREERS = OrderedDict(
    [
        ("CUL", "Cultivator"),
        ("SCH", "Arcane Scholar"),
        ("HAC", "Cyber Hacker"),
        ("UDW", "Underworld"),
        ("INF", "Influencer"),
        ("HEI", "Corporate Heir"),
        ("MEC", "Mechanic / Artisan"),
        ("MIL", "Military / PMC"),
        ("POL", "Politician"),
        ("CLT", "Cultist / Secret Society"),
    ]
)

LINE_RE = re.compile(
    r"^\s*-\s+\[(?P<done>[ xX\-])\]\s+`(?P<id>[A-Z0-9][A-Z0-9\-]*)`\s+"
    r"[—-]\s+(?P<body>.*?)\s*\[(?P<src>[SD])\]\s*\[(?P<pri>P[012])\]\s*$"
)
CHECKBOX_RE = re.compile(r"^\s*-\s+\[[ xX\-]\]")

STATUS_LABEL = {" ": "open", "x": "done", "X": "done", "-": "deferred"}


class Item:
    __slots__ = ("id", "body", "status", "src", "pri", "file", "line", "prefix", "domain")

    def __init__(self, **kw):
        for k, v in kw.items():
            setattr(self, k, v)


def prefix_of(asset_id: str) -> str | None:
    """Longest registered prefix that matches the ID."""
    best = None
    for p in PREFIXES:
        if (asset_id == p or asset_id.startswith(p + "-")) and (best is None or len(p) > len(best)):
            best = p
    return best


def parse(errors: list[str]) -> list[Item]:
    items: list[Item] = []
    seen: dict[str, str] = {}
    for path in sorted(DOCS.glob("*.md")):
        if path.name == "README.md":
            continue
        for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not CHECKBOX_RE.match(raw):
                continue
            m = LINE_RE.match(raw)
            loc = f"{path.name}:{n}"
            if not m:
                errors.append(f"{loc}: checkbox is not in canonical form -> {raw.strip()[:90]}")
                continue
            d = m.groupdict()
            aid = d["id"]
            pfx = prefix_of(aid)
            if pfx is None:
                errors.append(f"{loc}: unregistered ID prefix in `{aid}`")
                pfx = "?"
            if aid in seen:
                errors.append(f"{loc}: duplicate ID `{aid}` (first seen {seen[aid]})")
            else:
                seen[aid] = loc
            items.append(
                Item(
                    id=aid,
                    body=d["body"].strip().rstrip("."),
                    status=STATUS_LABEL[d["done"]],
                    src=d["src"],
                    pri=d["pri"],
                    file=path.name,
                    line=n,
                    prefix=pfx,
                    domain=PREFIXES.get(pfx, ("?", "?"))[0],
                )
            )
    return items


def group(items: list[Item], key) -> dict:
    out: dict[str, list[Item]] = defaultdict(list)
    for it in items:
        out[key(it)].append(it)
    return out


# --------------------------------------------------------------------------- #
# brief conformance
# --------------------------------------------------------------------------- #
def build_assertions(items):
    """Every numeric requirement stated in the original brief, as an executable check."""
    by_prefix = Counter(it.prefix for it in items)
    ids = {it.id for it in items}

    def cnt(p):
        return by_prefix.get(p, 0)

    def sub(p, part):
        return {i.id for i in items if i.prefix == p and f"-{part}-" in i.id}

    district_codes = {i.id.split("-")[1] for i in items if i.prefix == "ENV"}
    career_codes = {i.id.split("-")[1] for i in items if i.prefix == "CR"}
    melee_classes = {i.id.split("-")[2] for i in items if i.prefix == "WPN-MEL"}
    ranged_classes = {i.id.split("-")[2] for i in items if i.prefix == "WPN-RNG"}
    mel_classes_anm = {i.id.split("-")[2] for i in items if i.prefix == "ANM-MEL"}
    ma_styles = {i.id.split("-")[2] for i in items if i.prefix == "ANM-MA"}

    return [
        ("Base body frames == 5 (slim/athletic/average/heavy/tall)", cnt("CHR-BODY") == 5, cnt("CHR-BODY")),
        ("Face morph sliders >= 30", cnt("CHR-FACE") >= 30, cnt("CHR-FACE")),
        ("Hairstyles >= 40", cnt("CHR-HAIR") >= 40, cnt("CHR-HAIR")),
        ("Iris patterns >= 20", cnt("CHR-EYE") >= 20, cnt("CHR-EYE")),
        ("Scar / tattoo patterns >= 15", cnt("CHR-DECAL") >= 15, cnt("CHR-DECAL")),
        ("Districts == 12", district_codes == set(DISTRICTS), sorted(district_codes)),
        ("Every district has >= 8 kit deliverables", all(
            len([i for i in items if i.prefix == "ENV" and i.id.split("-")[1] == c]) >= 8
            for c in DISTRICTS
        ), min((len([i for i in items if i.prefix == "ENV" and i.id.split("-")[1] == c]) for c in district_codes), default=0)),
        ("Vehicles == 10 classes", cnt("VEH") >= 10, cnt("VEH")),
        ("Melee weapon classes == 6", melee_classes == {"FST", "DAG", "SWD", "GSW", "BLT", "POL"}, sorted(melee_classes)),
        ("Ranged weapon classes == 6", ranged_classes == {"PST", "SMG", "SHG", "RIF", "DMR", "SNP"}, sorted(ranged_classes)),
        ("Throwables >= 5", cnt("WPN-THR") >= 5, cnt("WPN-THR")),
        ("Melee movesets cover all 6 weapon classes", mel_classes_anm == {"FST", "DAG", "SWD", "GSW", "BLT", "POL"}, sorted(mel_classes_anm)),
        ("Martial arts styles == 6", len(ma_styles) == 6, sorted(ma_styles)),
        ("Spell drawing shapes == 6", cnt("MAG-SHP") == 6, cnt("MAG-SHP")),
        ("Persona auras == 10 (one per career)",
         {i.id.split("-")[1] for i in items if i.prefix == "AUR"} == set(CAREERS),
         sorted({i.id.split("-")[1] for i in items if i.prefix == "AUR"})),
        ("Career paths == 10", career_codes == set(CAREERS), sorted(career_codes)),
        ("Every career has wardrobe + tools + VFX", all(
            all(any(i.id.startswith(f"CR-{c}-{k}") for i in items) for k in ("W", "T", "V"))
            for c in CAREERS
        ), [c for c in CAREERS if not all(any(i.id.startswith(f"CR-{c}-{k}") for i in items) for k in ("W", "T", "V"))]),
        ("Workstations cover 4 benches", {i.id.split("-")[1] for i in items if i.prefix == "CFT"} == {"FRG", "ALC", "KIT", "ENC"},
         sorted({i.id.split("-")[1] for i in items if i.prefix == "CFT"})),
        ("Raw material families == 6", {i.id.split("-")[1] for i in items if i.prefix == "RAW"} == {"HERB", "ANIM", "MIN", "TECH", "CONT", "QI"},
         sorted({i.id.split("-")[1] for i in items if i.prefix == "RAW"})),
        ("Tactical reloads cover all 6 ranged classes",
         {"RIF", "PST", "SMG", "SHG", "DMR", "SNP"} <= {i.id for i in items if i.prefix == "ANM-TAC"} or
         len([i for i in items if i.prefix == "ANM-TAC" and "reload" in i.body.lower()]) >= 6,
         len([i for i in items if i.prefix == "ANM-TAC" and "reload" in i.body.lower()])),
    ]


# --------------------------------------------------------------------------- #
# roll-up
# --------------------------------------------------------------------------- #
def rollup(items: list[Item]) -> str:
    by_domain = group(items, lambda i: i.domain)
    by_prefix = group(items, lambda i: i.prefix)
    out = [ROLLUP_START, ""]
    out.append("## Progress roll-up")
    out.append("")
    total = len(items)
    done = sum(1 for i in items if i.status == "done")
    deferred = sum(1 for i in items if i.status == "deferred")
    p0 = sum(1 for i in items if i.pri == "P0")
    spec = sum(1 for i in items if i.src == "S")
    out.append(
        f"**{total} tracked assets** across {len(by_domain)} domains and "
        f"{len(by_prefix)} categories. "
        f"{done} done / {total - done - deferred} open / {deferred} deferred. "
        f"{p0} are P0 (vertical slice) and {spec} are specified in the original brief."
    )
    out.append("")
    out.append("| Domain | Categories | Items | P0 | Done | % |")
    out.append("| --- | ---: | ---: | ---: | ---: | ---: |")
    for dom in DOMAIN_ORDER:
        di = by_domain.get(dom, [])
        if not di:
            continue
        d = sum(1 for i in di if i.status == "done")
        pct = f"{round(100 * d / len(di))}%" if di else "-"
        out.append(
            f"| {dom} | {len({i.prefix for i in di})} | {len(di)} | "
            f"{sum(1 for i in di if i.pri == 'P0')} | {d} | {pct} |"
        )
    out.append(
        f"| **Total** | **{len(by_prefix)}** | **{total}** | **{p0}** | **{done}** | "
        f"**{round(100 * done / total) if total else 0}%** |"
    )
    out.append("")
    out.append("### By category")
    out.append("")
    out.append("| ID prefix | Category | Items | P0 | P1 | P2 | Done |")
    out.append("| --- | --- | ---: | ---: | ---: | ---: | ---: |")
    for dom in DOMAIN_ORDER:
        for pfx in sorted(by_prefix, key=lambda p: (DOMAIN_ORDER.index(PREFIXES[p][0]) if PREFIXES.get(p, ("?",))[0] in DOMAIN_ORDER else 99, p)):
            if PREFIXES.get(pfx, ("?",))[0] != dom:
                continue
            pi = by_prefix[pfx]
            out.append(
                f"| `{pfx}` | {PREFIXES[pfx][1]} | {len(pi)} | "
                f"{sum(1 for i in pi if i.pri == 'P0')} | {sum(1 for i in pi if i.pri == 'P1')} | "
                f"{sum(1 for i in pi if i.pri == 'P2')} | {sum(1 for i in pi if i.status == 'done')} |"
            )
    out.append("")
    out.append(ROLLUP_END)
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="rewrite the roll-up block in the index")
    ap.add_argument("--check", action="store_true", help="fail if the committed roll-up is stale")
    ap.add_argument("--csv", metavar="PATH", help="export all items to CSV")
    args = ap.parse_args()

    if not DOCS.is_dir():
        print(f"missing checklist dir: {DOCS}", file=sys.stderr)
        return 2

    errors: list[str] = []
    items = parse(errors)
    if not items:
        errors.append("no checklist items found")

    print(f"parsed {len(items)} checklist items from {DOCS.relative_to(ROOT)}")
    for name, ok, actual in build_assertions(items):
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + ("" if ok else f"  -> {actual}"))
        if not ok:
            errors.append(f"brief requirement not met: {name} (actual: {actual})")

    if args.csv:
        dest = Path(args.csv)
        dest.parent.mkdir(parents=True, exist_ok=True)
        with dest.open("w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(["id", "domain", "category", "status", "priority", "source", "file", "line", "description"])
            for it in items:
                w.writerow([it.id, it.domain, PREFIXES.get(it.prefix, ("", ""))[1],
                            it.status, it.pri, it.src, it.file, it.line, it.body])
        try:
            shown = dest.resolve().relative_to(ROOT)
        except ValueError:
            shown = dest
        print(f"wrote {len(items)} rows -> {shown}")

    if args.write or args.check:
        text = INDEX.read_text(encoding="utf-8")
        block = rollup(items)
        if ROLLUP_START not in text or ROLLUP_END not in text:
            print("index is missing the ROLLUP markers", file=sys.stderr)
            return 2
        head, _, rest = text.partition(ROLLUP_START)
        _, _, tail = rest.partition(ROLLUP_END)
        new = head + block + tail
        if args.write:
            if new != text:
                INDEX.write_text(new, encoding="utf-8")
                print("updated roll-up in", INDEX.relative_to(ROOT))
            else:
                print("roll-up already current")
        elif new != text:
            errors.append("roll-up in docs/asset-checklist/README.md is stale; run tools/check_checklist.py --write")

    if errors:
        print(f"\n{len(errors)} problem(s):", file=sys.stderr)
        for e in errors:
            print("  -", e, file=sys.stderr)
        return 1
    print("\nOK: checklist is well-formed and satisfies every numeric requirement in the brief.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
